### ISSUE TITLE
[FEATURE] User Authentication via Passport.js

### ISSUE THREAD

**Issue by ABsolutelyWeb** [ggkfox/CSCI-150#10]
Using Passport.js to configure user authentication.

**Comment by Alan947** [comment]
How is password recovery implemented (for documentation purposes)? Is it a typical password recovery via email?

**Comment by ABsolutelyWeb** [comment]
There is no password recovery as of now and I don't see password recovery being a thing currently.

**Comment by ABsolutelyWeb** [comment]
Josh pushed the final changes to the user accounts / authentication implementation. Issue has been closed.
