### ISSUE TITLE
[BUG] We need to have more employees than stations or app behaves weirdly

### ISSUE THREAD

**Issue by ABsolutelyWeb** [ggkfox/CSCI-150#19]
When we have more stations than employees, the application behaves strangely. We can either fix this or assume the program will always have more employees than stations.

**Comment by Alan947** [comment]
This might be fixed the ignoring certain stations, BUT only for certain work environments (given that stations must be filled at all time as required by law for waterparks). If there are more stations than there are employees then maybe we can just allow the algorithm to filter through, say, x number of stations.

**Comment by n1k3light** [comment]
What if we have more employees than stations. Will some people have short days ??

**Comment by n1k3light** [comment]
What if we have more employees than stations.?

**Comment by Alan947** [comment]
Ab said the problem is present when there are more stations than employees so more an employees than stations is working properly.

**Comment by ABsolutelyWeb** [comment]
Fixed it. Release v3.0 and current master have these changes reflected.
