### ISSUE TITLE
[FEATURE] maintenance.ejs Someone Needs to Work On This Page

### ISSUE THREAD

**Issue by ABsolutelyWeb** [ggkfox/CSCI-150#9]
This page needs styling.

**Comment by SKennedy94** [comment]
Dibs

**Comment by n1k3light** [comment]
Im working on it as we speak, just understanding the html and css  and how to link them together, but progress is being made. There should be something to display

**Comment by n1k3light** [comment]
The issue has been resolved and have been styled to perfection as possible, with this said issue is closed
